### ISSUE TITLE
error during  allc to bigwig conversion

### ISSUE THREAD

**Issue by shahsam** [yupenghe/methylpy#12]
I am trying to convert allc files to bigwig but I am getting some errors. Here is the command I ran:

`$methylpy allc-to-bigwig --allc-file wtCol_R1_A_s.tsv --output wtCol_R1_A_s_CHH.bw --ref-fasta ../../../data/ref_annot/TAIR10.fasta --mc-type CHH --bin-size 100`
The wigToBigWig script is installed in my PATH, I also ran methylpy by specifying the path, but I get the same error.

##########
```
Traceback (most recent call last):
  File "/Users/xxxx/anaconda3/bin/methylpy", line 4, in <module>
    __import__('pkg_resources').run_script('methylpy==1.3.1', 'methylpy')
  File "/Users/xxxx/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/xxxx/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/Users/xxxx/anaconda3/lib/python3.6/site-packages/methylpy-1.3.1-py3.6.egg/EGG-INFO/scripts/methylpy", line 5, in <module>
    parse_args()
  File "/Users/xxxx/anaconda3/lib/python3.6/site-packages/methylpy-1.3.1-py3.6.egg/methylpy/parser.py", line 313, in parse_args
    add_chr_prefix=args.add_chr_prefix)
  File "/Users/xxxx/anaconda3/lib/python3.6/site-packages/methylpy-1.3.1-py3.6.egg/methylpy/utilities.py", line 252, in convert_allc_to_bigwig
    +output_file),stderr=subprocess.PIPE)
  File "/Users/xxxx/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wigToBigWig', 'wtCol_R1_A_s_CHH.bw.wig', 'wtCol_R1_A_s_CHH.bw.chrom_size', 'wtCol_R1_A_s_CHH.bw']' returned non-zero exit status 255.
```

**Comment by yupenghe** [comment]
Hi, 
I would check:
1. If you run `wigToBigWig` directly, can you see the help information? Just to check weather `wigToBigWig` is granted execution permission. 

2. Can you share the first 10 lines of `wtCol_R1_A_s_CHH.bw.wig` and `wtCol_R1_A_s_CHH.bw.chrom_size`? Just to infer the potential issue.

Yupeng

**Comment by shahsam** [comment]
Hi Yupeng, 
1. I can see the help info. if I run wigToBigWig directly.
2. Here are the first ten lines of the relevant files:

```
$ head -10 wtCol_R1_A_s_CHH.bw.wig 
1	0	100	0.042735042735042736
1	100	200	0.09057971014492754
1	200	300	0.028037383177570093
1	300	400	0.015909090909090907
1	400	500	0.040339702760084924
1	500	600	0.011741682974559686
1	600	700	0.028795811518324606
1	700	800	0.04316546762589928
1	800	900	0.09055118110236221
1	900	1000	0.020080321285140562
```

```
$ head -10 wtCol_R1_A_s_CHH.bw.chrom_size 
chr1	30427671
chr2	19698289
chr3	23459830
chr4	18585056
chr5	26975502
chrC	154478
chrM	366924
```
First ten lines of my allc input:
```
$ head -10 wtCol_R1_A_s.tsv 
1	1	+	CCC	0	1	0	CHH
1	2	+	CCT	0	2	0	CHH
1	3	+	CTA	0	2	0	CHH
1	8	+	CCC	0	2	0	CHH
1	9	+	CCT	0	2	0	CHH
1	10	+	CTA	0	2	0	CHH
1	15	+	CCC	0	2	0	CHH
1	16	+	CCT	0	2	0	CHH
1	17	+	CTA	0	2	0	CHH
1	22	+	CCC	0	4	0	CHH
```
The chromosome names in my genome file do not have "chr" (shown below), but those in wtCol_R1_A_s_CHH.bw.chrom_size file have 'chr' --may be that's the reason I am getting this error?
```
$ grep ">" ../../../data/ref_annot/TAIR10.fasta
>1
>2
>3
>4
>5
>C
>M
```

**Comment by yupenghe** [comment]
Exactly, adding "--add-chr-prefix True" will fix the problem.

**Comment by shahsam** [comment]
Works now, thanks!
