### ISSUE TITLE
ValueError: percentile must be in the range [0, 100]

### ISSUE THREAD

**Issue by shahsam** [yupenghe/methylpy#14]
Hey Yupeng, I have run into some issues while running a full DMRfind pipeline. Could you suggest if the errors are due to the options I used in the following command?

`$methylpy DMRfind --allc-files A.tsv .B.tsv --samples A B  --chroms 1 2 3 4 5 --mc-type CHH --output-prefix AB --resid-cutoff 2 --min-num-dms 4`

At the FDR correction stage, I get the following error messages:

```
Begin FDR Correction
Mon May 21 16:13:09 2018

m0 estimate for iteration 0: 3819203
Histogram FDR correction did not converge. Using the smallest p-value 0.0003333333333333333 as cutoff.

Calculating Residual Cutoff
Mon May 21 16:13:11 2018

Traceback (most recent call last):
  File "/Users/x/anaconda3/bin/methylpy", line 4, in <module>
    __import__('pkg_resources').run_script('methylpy==1.3.2', 'methylpy')
  File "/Users/x/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/x/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/Users/x/anaconda3/lib/python3.6/site-packages/methylpy-1.3.2-py3.6.egg/EGG-INFO/scripts/methylpy", line 5, in <module>
    parse_args()
  File "/Users/x/anaconda3/lib/python3.6/site-packages/methylpy-1.3.2-py3.6.egg/methylpy/parser.py", line 71, in parse_args
    seed=args.seed)
  File "/Users/x/anaconda3/lib/python3.6/site-packages/methylpy-1.3.2-py3.6.egg/methylpy/DMRfind.py", line 274, in DMRfind
    convergence_diff=convergence_diff)
  File "/Users/x/anaconda3/lib/python3.6/site-packages/methylpy-1.3.2-py3.6.egg/methylpy/DMRfind.py", line 319, in merge_DMS_to_DMR
    input_rms_file)
  File "/Users/x/anaconda3/lib/python3.6/site-packages/methylpy-1.3.2-py3.6.egg/methylpy/DMRfind.py", line 487, in get_resid_cutoff
    return scoreatpercentile(residuals, resid_cutoff)
  File "/Users/x/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py", line 1590, in scoreatpercentile
    return _compute_qth_percentile(sorted, per, interpolation_method, axis)
  File "/Users/x/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py", line 1601, in _compute_qth_percentile
    raise ValueError("percentile must be in the range [0, 100]")
ValueError: percentile must be in the range [0, 100]
```

**Comment by yupenghe** [comment]
Hi, it was due to `--resid-cutoff 2`. The value passed --resid-cutoff must be between 0 and 1. The higher the value, the less stringent to call a sample hyper- or hypomethylated at a given tested cytosine. 

If you keep the output from `methylpy DMRfind`, you can start from there with `methylpy reidentify-DMR`.

Yupeng
