### ISSUE TITLE
error in testing single-end-pipeline with bowtie

### ISSUE THREAD

**Issue by shahsam** [yupenghe/methylpy#17]
Hi Yupeng, I am trying to test my methylpy installation on a Linux machine, but the run_test.py fails at the stage of testing single-end-pipeline with bowtie. How can I fix this? Below is the terminal output:

```
$ python run_test.py 
Tests start
Thu Aug 16 10:07:48 2018

Test importing methylpy module.
- importing call_mc_se: pass
- importing call_mc_pe: pass
- importing DMRfind: pass
- importing parser: pass
Check methylpy executable:pass

methylpy is successfully installed!

Check whether dependencies are available in PATH
- find bowtie: found version 1.2.2
- find bowtie2: found version 2.3.4.1
- find minimap2: failed
- find samtools: found version 1.9
- find cutadapt: found version 1.16
- find java: found version 1.8.0_171
Both bowtie and bowtie2 are available and will be tested.

Test DMRfind: pass
Test reidentify-DMR: pass

Test build-reference with bowtie: pass
Test build-reference with bowtie2: pass

Test single-end-pipeline with bowtie: Traceback (most recent call last):
  File "run_test.py", line 204, in <module>
    stderr=f_stderr)
  File "/home/x/miniconda3/envs/methylpy/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['methylpy', 'single-end-pipeline', '--read-files', 'data/test_data_R1.fastq.gz', '--sample', 'se_bt', '--path-to-output', 'results/', '--forward-ref', 'chrL/chrL_f', '--reverse-ref', 'chrL/chrL_r', '--ref-fasta', 'data/chrL.fa', '--num-procs', '1', '--aligner', 'bowtie', '--bgzip', 'True', '--aligner', 'bowtie', '--path-to-aligner', '', '--path-to-samtools', '', '--remove-clonal', 'False', '--trim-reads', 'False', '--binom-test', 'True', '--unmethylated-control', '0.005']' returned non-zero exit status 1.
```

Here is the content of test_error_msg.txt generated :
```$ more test_error_msg.txt 
/home/x/miniconda3/envs/methylpy/lib/python3.6/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq
)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
/home/x/miniconda3/envs/methylpy/lib/python3.6/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq
)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
Building a SMALL index
Building a SMALL index
# reads processed: 93996
# reads with at least one reported alignment: 44539 (47.38%)
# reads that failed to align: 49457 (52.62%)
Reported 44539 alignments
# reads processed: 93996
# reads with at least one reported alignment: 44443 (47.28%)
# reads that failed to align: 49553 (52.72%)
Reported 44443 alignments
[mpileup] 1 samples in 1 input files
Traceback (most recent call last):
  File "/home/x/miniconda3/envs/methylpy/bin/methylpy", line 4, in <module>
    __import__('pkg_resources').run_script('methylpy==1.3.4', 'methylpy')
  File "/home/x/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/x/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/shares/x_share/private/x/miniconda3/envs/methylpy/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/EGG-INFO/scripts/methylpy", line 5, in <module>
    parse_args()
  File "/home/x/miniconda3/envs/methylpy/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/methylpy/parser.py", line 134, in parse_args
    keep_temp_files=args.keep_temp_files)
  File "/home/x/miniconda3/envs/methylpy/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/methylpy/call_mc_se.py", line 323, in run_methylation_pipeline
    keep_temp_files=keep_temp_files)
  File "/home/x/miniconda3/envs/methylpy/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/methylpy/call_mc_se.py", line 1644, in call_methylated_sites
    bgzip_allc_file(output_file,path_to_bgzip,path_to_tabix,buffer_line_number)
  File "/home/x/miniconda3/envs/methylpy/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/methylpy/utilities.py", line 66, in bgzip_allc_file
    output_pipe.stdin.write(out)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by yupenghe** [comment]
Hi Saima,
You should be good to go. The test failed because bgzip and/or tabix are
not installed. They are not required for using methylpy. I will modify test
so such error won’t appear again.

Yupeng

**Comment by shahsam** [comment]
Thanks Yupeng, really appreciate your prompt response. I actually have tabix and bgzip 1.9 installed, but looks like these are not found during the test.

**Comment by yupenghe** [comment]
I modified the methylpy test. Are you able to pass all the test?

**Comment by shahsam** [comment]
It works beautifully -- all tests passed! Thanks so much :)
