### ISSUE TITLE
error in mapping.

### ISSUE THREAD

**Issue by CS791** [yupenghe/methylpy#21]
Hi! yupenghe,

I am using methylpy first time and I am not very good in computer programming.
Any help will be much appreciated.

I am trying to map my paired-end reads to transposable elements of Arabidopsis with the following command line:
**   methylpy paired-end-pipeline --read1-files New_Analysis/Data/Epiril368_4_C_R1_L001_R1.fastq.gz --read2-files New_Analysis/Data/Epiril368_4_C_R1_L001_R2.fastq.gz --sample New_Analysis/New_Output/TE/epiRIL368_4°C_Rep1_Lane1_TE --forward-ref New_Analysis/TE_Genome/TAIR10_TE_f --reverse-ref New_Analysis/TE_Genome/TAIR10_TE_r --ref-fasta New_Analysis/TE_Genome/TAIR10_TE.fas --generate-allc-file True  --num-procs 4 --compress-output True  --remove-clonal True --path-to-picard="picard/"    ** 
But with alignment I got the following warnings:

**Traceback (most recent call last):
  File "/home/saurabh/anaconda3/bin/methylpy", line 4, in <module>
    __import__('pkg_resources').run_script('methylpy==1.3.4', 'methylpy')
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/EGG-INFO/scripts/methylpy", line 5, in <module>
    parse_args()
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/methylpy/parser.py", line 185, in parse_args
    keep_temp_files=args.keep_temp_files)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/methylpy/call_mc_pe.py", line 342, in run_methylation_pipeline_pe
    keep_temp_files=keep_temp_files)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/methylpy/call_mc_pe.py", line 1343, in call_methylated_sites_pe
    path_to_samtools=path_to_samtools)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/methylpy/call_mc_pe.py", line 1265, in flip_read2_strand
    for line in input_pipe.stdout:
  File "/home/saurabh/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 509: invalid start byte**

I don't understand exactly what it is.

Thank you!
Regards
CS791

**Comment by yupenghe** [comment]
Hey CS791,
Is this error reproducible? If you run your command again, will you get the same error?

Yupeng

**Comment by CS791** [comment]
Hello! Yupeng,

Thank you! for your reply. 
Yes! it does reproducible and I got the same error when I run with same input as well as other input files.

Thank you. 
Regards

CS791

**Comment by yupenghe** [comment]
Ok. If you use python2 instead of python3, would you still see this problem? This may be the quickest fix.

What output/intermediate files were generated when you ran methylpy? What are their sizes? Would it be possible for you to share some input files for me to reproduce this error? Thanks.

**Comment by CS791** [comment]
Thanks again.
I will try with python2 instead of python3, and let you know.
As far as output files are concerned, surprisingly I got only two bam files of sizes around 216 MB. That might be possible as my reference is only transposable element genes, not the whole genome.
But I am not able to generate allc files.
Thank you! for suggestions.
I will let you know once I will do with python2
