### ISSUE TITLE
Error with new picard version

### ISSUE THREAD

**Issue by rbpisupati** [yupenghe/methylpy#33]
Hi, 

I get an error with methylpy with new picard version. Since picard has its own binary instead of jar file, methylpy is searching for picard.jar, can you please update this?

Here is the error
> Error: Unable to access jarfile /picard.jar
Traceback (most recent call last):
  File "\~/.conda/envs/methylpy/bin/methylpy", line 5, in <module>
    parse_args()
  File "\~/.conda/envs/methylpy/lib/python3.7/site-packages/methylpy/parser.py", line 185, in parse_args
    keep_temp_files=args.keep_temp_files)
  File "\~/.conda/envs/methylpy/lib/python3.7/site-packages/methylpy/call_mc_pe.py", line 276, in run_methylation_pipeline_pe
    java_options=java_options)
  File "\~/.conda/envs/methylpy/lib/python3.7/site-packages/methylpy/call_mc_se.py", line 1338, in remove_clonal_bam
    "QUIET=true"])
  File "\~/.conda/envs/methylpy/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-Djava.io.tmpdir=/scratch-cbe/tempFiles', '-jar', '/picard.jar', 'MarkDuplicates', 'INPUT=CBURWANXX_4#GCGTAGTA_719_libA_processed_reads.bam', 'OUTPUT=CBURWANXX_4#GCGTAGTA_719_libA_processed_reads_no_clonal.bam', 'ASSUME_SORTED=true', 'REMOVE_DUPLICATES=true', 'METRICS_FILE=CBURWANXX_4#GCGTAGTA_719_libA.metric', 'VALIDATION_STRINGENCY=LENIENT', 'QUIET=true']' returned non-zero exit status 1.

Cheers
r

**Comment by yupenghe** [comment]
jar is still one of the release form of the latest version of Picard (https://github.com/broadinstitute/picard/releases/tag/2.20.4). I am not sure whether most people use binary or jar. I prefer not to change unless there are clear advantages.
