### ISSUE TITLE
cutadapt error for methylpy v 1.4.6

### ISSUE THREAD

**Issue by shahsam** [yupenghe/methylpy#69]
Hi Yupeng,

I am getting some strange error for cutadapt (3.4) after upgrading methylpy from 1.4.2 to 1.4.6. Here is the error message:

```
cutadapt: error: unrecognized arguments: -f x_libA_split_4
Run "cutadapt --help" to see command-line options.
```
And this is reported for all split files.  here is the rest of the error log:
```
rm: cannot remove ‘x_libA_split_trimmed_0’: No such file or directory
.....
rm: cannot remove ‘x_libA_split_trimmed_19’: No such file or directory

Traceback (most recent call last):
  File "/home/.local/bin/methylpy", line 5, in <module>
    parse_args()
  File "/home/.local/lib/python3.6/site-packages/methylpy/parser.py", line 134, in parse_args
    keep_temp_files=args.keep_temp_files)
  File "/home/.local/lib/python3.6/site-packages/methylpy/call_mc_se.py", line 244, in run_methylation_pipeline
    sort_mem=sort_mem)
  File "/home/.local/lib/python3.6/site-packages/methylpy/call_mc_se.py", line 481, in run_mapping
    for i in range(0,num_procs)])))
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rm', 'x_libA_split_trimmed_0', ....., 'x_libA_split_trimmed_19']' returned non-zero exit status 1.
```
Below is my code for methylpy (which worked fine for cutadapt 2.10, methylpy 1.4.2)
```
methylpy single-end-pipeline \
	 --read-files file.fastq.gz \
	 --sample x  \
	 --trim-reads True --path-to-cutadapt "/home/miniconda3/envs/methylpy/bin/" \
	 --unmethylated-control ChrL: \
	 --path-to-samtools "/home/bin/" \
	 --path-to-aligner "/home/bin/" \
	 --forward-ref /home/ref_genome_f \
	 --reverse-ref /home/ref_genome_r \
	 --ref-fasta /home/ref_genome.fa \
	 --num-procs 20 \
	 --remove-clonal True \
	 --path-to-picard "/home/bin/" \
	 --compress-output True \
```
Could you help me to figure out how to fix this? thanks.

Update:
Just to clarify - I saw that the split files are generated in my home directory initially. After the run is aborted due to the above errors, the temporary files are gone. I also tried running the command by specifying the path to output, it still showed me errors for split file not found.

**Comment by shahsam** [comment]
I think I figured out the issue -f parameter is deprecated in cutadapt v3.1+

**Comment by yupenghe** [comment]
Cool. Do you need any help with this? Downgrading cutadapt to the version methylpy supported is one option. Alternatively, we can run cutadapt manually and then run methylpy with trimming step turned off.

**Comment by hyphaltip** [comment]
FYI - success here with downgrade to 2.10 eg after building the env I forced the cutadapt version down to 2.x
```
conda install cutadapt=2.10
```
