### ISSUE TITLE
Issue with Methylpy Single-End-Pipeline Using “–pbat True”

### ISSUE THREAD

**Issue by riverwin1207** [yupenghe/methylpy#92]
Hi Yupeng,

Hope you are doing well.

I am encountering an issue while running the Methylpy single-end-pipeline with the “–pbat True” option. During the read splitting process, Methylpy unexpectedly halts with the error message below.

Traceback (most recent call last):
  File "/path_to_methylpy/methylpy", line 5, in <module>
    parse_args()
  File "/path_to/methylpy/parser.py", line 134, in parse_args
    keep_temp_files=args.keep_temp_files)
  File "/path_to_methylpy/methylpy/call_mc_se.py", line 242, in run_methylation_pipeline
    sort_mem=sort_mem)
  File "/path_to_methylpy/methylpy/call_mc_se.py", line 439, in run_mapping
    total_input = split_fastq_file_pbat(num_procs, library_files, file_path+"_split_")
  File "/path_to_methylpy/methylpy/utilities.py", line 849, in split_fastq_file_pbat
    file_handles[current_file].write(reverse_complement(line)+"\n")
  File "/path_to_methylpy/methylpy/utilities.py", line 817, in reverse_complement
    return("".join([complement[base] for base in reversed(dna)]))
  File "/path_to_methylpy/methylpy/utilities.py", line 817, in <listcomp>
    return("".join([complement[base] for base in reversed(dna)]))
KeyError: '5'

This issue only arises with a specific FASTQ file (DRR159248). Upon multiple attempts, I noticed that the number of processed (split) reads varied each time. Actually I have three FASTQ files prepared using PBAT. The other two FASTQ files (DRR159247 and DRR159249) were processed without any issues.

I would greatly appreciate any insights into what might be causing this problem. Please let me know if you need any additional information to assist in troubleshooting this issue.

**Comment by riverwin1207** [comment]
Problem solved. I checked the md5 checksum  and found the FASTQ was incomplete. I downloaded FASTQ four times and finally got the complete FASTQ. Now methypy is working very fine.
